# Generated by Django 2.2.11 on 2020-04-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalcrossingnews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsStoryText',
            new_name='Story',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='Heading',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='newsStory_text',
            new_name='story_text',
        ),
    ]
